name       : python-yarl
version    : 1.3.0
release    : 3
source     :
    - https://github.com/aio-libs/yarl/archive/v1.3.0.tar.gz : 0d4acfd6c750612871e11c49eea43213949f1528686a184eefc1366142a6fbb3
license    : Apache-2.0
component  : programming.python
summary    : Yet another URL library
description: |
    Yet another URL library
builddeps  :
    - cython
rundeps    :
    - python-idna
    - python-multidict
build      : |
    %python3_setup
install    : |
    %python3_install
